name: Tests

on:
  push:
    branches:
      - main
  pull_request:

# jobs:
#   PyTest:
#     runs-on: ubuntu-latest
#     # container: pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: "3.8"
#       - name: Install Dependencies
#         run: |
#           curl -sSL https://install.python-poetry.org | python3 -
#           poetry install
#       - name: pytest
#         run: poetry run pytest muograph/test

jobs:
  PyTest:
    runs-on: ubuntu-latest
    # container: pytorch/pytorch:1.8.1-cuda11.1-cudnn8-runtime
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install Poetry 1.8.5
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --version 1.8.5
      - name: Verify Poetry Version
        run: poetry --version
      - name: Install Dependencies
        run: poetry install
      - name: Run Tests
        run: poetry run pytest muograph/test